<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Diamond extends Model
{
    protected $fillable = [
        'stock_id',
        'availability',
        'report_no',
        'shape',
        'carat',
        'color',
        'clarity',
        'cut',
        'polish',
        'symmetry',
        'fluorescence',
        'rap_price',
        'discount',
        'per_ct',
        'total',
        'sale_discount_percent',
        'sale_per_ct',
        'sale_total',
        'hold_name',
        'h_and_a',
        'remark',
        'lab',
        'cut_no',
        'country',
        'state',
        'city',
        'bgm',
        'eye_clean',
        'treatment',
        'growth_type',
        'company',
        'laser_inscription',
        'measurement',
        'table',
        'depth',
        'cr_ang',
        'cr_ht',
        'pv_ang',
        'pv_ht',
        'ratio',
        'girdle_percent',
        'length',
        'width',
        'height',
        'girdle_condition',
        'culet',
        'video_link',
        'image_link',
        'cert_pdf_link',
        'origin',
        'digital_report',
        'r1',
        'r2',
        'seagoma',
        'full_fancy_color',
        'fancy_color',
        'fancy_overtone',
        'fancy_intensity',
        'comment',
        'export_inv_no',
        'export_total_usd',
        'export_date',
        'import_date',
    ];
}
